name: CI/CD

on: push

env:
    maven_packages_cache: .m2/repository

jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v2

        - name: Maven Compile
          run: mvn compile

        - name: Cache
          uses: actions/cache@v2
          with:
            path: env.maven_packages_cache
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

        - name: Store artifacts
          uses: actions/upload-artifact@v2
          with:
            path: target/*
    
    test:
        needs: build
        runs-on: self-hosted
        
        steps:
        - name: Maven Test
          run: mvn test
          
        - name: Cache
          uses: actions/cache@v2
          with:
            path: env.maven_packages_cache
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            
        - name: Store artifacts
          uses: actions/upload-artifact@v2
          with:
            path: |
                target/surefire-reports/*
                target/site/jacoco/*

    package:
        needs: build
        runs-on: self-hosted
        
        steps:
        - name: Maven Package
          run: mvn test
          
        - name: Cache
          uses: actions/cache@v2
          with:
            path: env.maven_packages_cache
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            
        - name: Store artifacts
          uses: actions/upload-artifact@v2
          with:
            path: target/*.war
            
    deploy_test:
        needs: package
        runs-on: self-hosted

        steps:
        - uses: chrnorm/deployment-action@releases/v1
          name: Create GitHub deployment
          id: deployment
          with:
            token: "${{ github.token }}"
            target_url: http://localhost:8080/game2048
            environment: test
