name: CI/CD

on: push

env:
    maven_packages_cache: .m2/repository

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Maven Compile
      run: mvn compile
      
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: env.maven_packages_cache
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        path: target/*
